---
title: Real Estate With Ofir Eyal Bar
timezone: Pacific/Pago_Pago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: false
    social-share: true
    readtime: false
- scope:
    path: ''
  values:
    layout: page
    show-avatar: true
description: Real Estate With Ofir Eyal Bar
author: Ofir Eyal Bar
navbar-links:
  About Me: "/aboutme"
  Blog: "/blog"
  News: "/"
avatar: "/uploads/5.png"
round-avatar: true
social-network-links:
  email: info@buzzdealer.com
  facebook: 
  twitter: ofireyalbar
  youtube: channel/UCJ3SuUW3IsRzJu4x2SBk2yw
  instagram: ofireyalbar
  pinterest: ofireyalbar
  rss: true
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
url-pretty: ofireyalbar.me
link-tags: true
excerpt_length: 100
navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-border-col: "#EAEAEA"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#004ba1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"
title-separator: "-"
date_format: "%B %-d, %Y"
markdown: kramdown
highlighter: rouge
permalink: "/:year-:month-:day-:title/"
paginate: 5
newsletter: false
kramdown:
  input: GFM
exclude:
- CHANGELOG.md
- CNAME
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- screenshot.png
- docs/
plugins:
- jekyll-paginate
- jekyll-sitemap
