---
title: BuzzDealer Tech Blog
timezone: America/Vancouver
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
    social-share: true
    readtime: false
- scope:
    path: ''
  values:
    layout: page
    show-avatar: true
description: Technical blog of buzzdealer Ltd
author: Isak
navbar-links:
  About Me: aboutme
  Resources:
  - Beautiful Jekyll: https://beautifuljekyll.com
  - Learn markdown: https://www.markdowntutorial.com/
  Author's home: https://deanattali.com
avatar: "/assets/img/avatar-icon.png"
round-avatar: true
social-network-links:
  email: info@buzzdealer.com
  facebook: deanattali
  github: daattali
  twitter: daattali
  rss: true
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
url-pretty: Buzzdealer.com
link-tags: true
excerpt_length: 50
navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-border-col: "#EAEAEA"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"
title-separator: "-"
date_format: "%B %-d, %Y"
markdown: kramdown
highlighter: rouge
permalink: "/:year-:month-:day-:title/"
paginate: 5
kramdown:
  input: GFM
exclude:
- CHANGELOG.md
- CNAME
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- screenshot.png
- docs/
plugins:
- jekyll-paginate
- jekyll-sitemap
